# Generated by Django 4.0 on 2023-02-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('CODE', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('NAME_USER', models.CharField(max_length=30)),
                ('SECTION', models.CharField(max_length=30)),
                ('PASSWORD', models.CharField(max_length=30)),
                ('PERMITION', models.CharField(default='E', max_length=5)),
                ('INSERTTIME', models.DateTimeField(auto_now_add=True)),
                ('UPDATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record_histrory',
            fields=[
                ('CODE_JOB', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('CODE', models.CharField(max_length=30)),
                ('Project_Code', models.CharField(max_length=30)),
                ('PONo', models.CharField(max_length=30)),
                ('Item_No', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
                ('Unit_of_Measure', models.CharField(max_length=30)),
                ('Start_Time', models.DateTimeField(auto_now_add=True)),
                ('Ending_Time', models.DateTimeField(auto_now_add=True)),
                ('Run_Time', models.IntegerField(max_length=255)),
                ('Work_by', models.CharField(max_length=30)),
                ('min_pcs', models.CharField(max_length=30)),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
