# Generated by Django 4.0 on 2023-04-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_itemno', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_qty', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Record_histrory',
        ),
    ]
