# Generated by Django 4.0 on 2023-04-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0002_product_delete_record_histrory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_ob',
        ),
    ]
