# Generated by Django 4.0 on 2023-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0003_rename_product_product_ob'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ob',
            name='timein',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
