# Generated by Django 4.0 on 2023-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0004_product_ob_timein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ob',
            name='product_itemno',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
