# Generated by Django 4.0 on 2023-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0005_alter_product_ob_product_itemno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ob',
            name='timein',
            field=models.DateTimeField(),
        ),
    ]
