# Generated by Django 4.0 on 2023-04-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0007_alter_product_ob_timein'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_rack_name',
            fields=[
                ('rack_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location_rack',
            fields=[
                ('rack_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack_no', models.IntegerField()),
                ('rack_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OutsouceInspection.location_rack_name')),
            ],
        ),
        migrations.CreateModel(
            name='Location_list',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('Location_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OutsouceInspection.location_rack')),
            ],
        ),
    ]
