# Generated by Django 4.0 on 2023-04-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0008_location_rack_name_location_rack_location_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_location',
            fields=[
                ('product_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('Location_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OutsouceInspection.location_list')),
                ('Product_ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OutsouceInspection.product_ob')),
            ],
        ),
    ]
