# Generated by Django 4.0 on 2023-04-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0009_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_list',
            name='Is_actie',
            field=models.IntegerField(null=True),
        ),
    ]
