# Generated by Django 4.0 on 2023-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0010_location_list_is_actie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_list',
            name='Is_actie',
        ),
        migrations.AddField(
            model_name='location_list',
            name='Is_active',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
