# Generated by Django 4.0 on 2023-04-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OutsouceInspection', '0011_remove_location_list_is_actie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custormer',
            fields=[
                ('custormer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='report_po',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('Custormer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OutsouceInspection.custormer')),
            ],
        ),
        migrations.CreateModel(
            name='product_arrival',
            fields=[
                ('arrival_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_arrival_no', models.CharField(max_length=255)),
                ('location_arrival_name', models.CharField(max_length=255)),
                ('timeupdate', models.DateTimeField(auto_now=True)),
                ('arrival_report', models.IntegerField(default=0, null=True)),
                ('Product_ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OutsouceInspection.product_ob')),
            ],
        ),
    ]
